### ISSUE TITLE
Version 1.5 App closes when clicking on  CGM in settings

### ISSUE THREAD

**Issue by CSlycord1** [Artificial-Pancreas/iAPSdocs#7]
New build this AM (1.5). on iPhone 12 mini.  iOS 16.4.1

Setting up initial settings, CGM, preferences, etc.  I have set CGM and finally getting data on iAPS and NS, but during set up I tried to go back into the settings and the app closes back to phone home screen.  This behavior repeats itself.

**Comment by sethgagnon** [comment]
This is the iAPS documentation repository. You will need to open an issue against the iAPS repo. Thanks
